/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */
/* EcoBridge Economy System - High-Performance Rust Engine */
/* For use with Java 25 Project Panama (Foreign Function API) */

#ifndef ECOBRIDGE_RUST_H
#define ECOBRIDGE_RUST_H

#include <stdint.h>
#include <stdbool.h>

#define DEFAULT_INTEGRATION_LIMIT 30.0

#define MAX_SAFE_DT 1.0

#define MIN_TIME_STEP 1e-6

#define OUTPUT_MIN_CLAMP 0.5

#define OUTPUT_MAX_CLAMP 5.0

#define OUTPUT_BASELINE 1.0

#define INTEGRAL_DECAY 0.99999

#define BACK_CALC_GAIN 0.2

#define DERIVATIVE_FILTER_ALPHA 0.3

#define PANIC_THRESHOLD 50.0

#define PANIC_DAMPING 1.8

#define HEAT_SENSITIVITY 0.5

#define CODE_NORMAL 0

#define CODE_WARNING_HIGH_RISK 1

#define CODE_BLOCK_REVERSE_FLOW 2

#define CODE_BLOCK_INJECTION 3

#define CODE_BLOCK_INSUFFICIENT_FUNDS 4

#define CODE_BLOCK_VELOCITY_LIMIT 5

#define CODE_BLOCK_QUANTITY_LIMIT 6

/*
 交易定价演算上下文 (64 bytes)
 */
typedef struct {
  long long base_price_micros;
  long long current_amount;
  double inflation_rate;
  long long current_timestamp;
  long long play_time_seconds;
  int timezone_offset;
  int newbie_mask;
  double market_heat;
  double eco_saturation;
} TradeContext;

/*
 市场动态定价配置 (72 bytes)
 */
typedef struct {
  double base_lambda;
  double volatility_factor;
  double seasonal_amplitude;
  double weekend_multiplier;
  double newbie_protection_rate;
  double seasonal_weight;
  double weekend_weight;
  double newbie_weight;
  double inflation_weight;
} MarketConfig;

/*
 交易演算最终结果 (16 bytes)
 */
typedef struct {
  long long final_tax_micros;
  int is_blocked;
  int warning_code;
} TransferResult;

/*
 交易审计上下文 (96 bytes)
 */
typedef struct {
  long long amount_micros;
  long long sender_balance;
  long long receiver_balance;
  double inflation_rate;
  long long item_base_limit;
  double item_growth_rate;
  long long item_max_limit;
  long long sender_play_time;
  long long receiver_play_time;
  double sender_activity_score;
  double sender_velocity;
  long long _padding;
} TransferContext;

/*
 审计监管与计税配置 (96 bytes)
 */
typedef struct {
  double base_tax_rate;
  long long luxury_threshold;
  double luxury_tax_rate;
  double wealth_gap_tax_rate;
  long long poor_threshold;
  long long rich_threshold;
  double _reserved;
  double warning_ratio;
  long long warning_min_amount;
  double newbie_hours;
  double veteran_hours;
  double velocity_threshold;
} RegulatorConfig;

/*
 工业级 PID 控制器状态 (72 bytes)
 */
typedef struct {
  double kp;
  double ki;
  double kd;
  double lambda;
  double integral;
  double prev_pv;
  double filtered_d;
  double integration_limit;
  int is_saturated;
  int _padding;
} PidState;

int ecobridge_abi_version(void);

const char *ecobridge_version(void);

int ecobridge_init_threading(int num_threads);

int ecobridge_init_db(const char *path_ptr);

int ecobridge_shutdown_db(void);

int ecobridge_log_to_duckdb(long long ts,
                            const char *uuid_ptr,
                            long long trade_amount_micros,
                            long long balance_micros,
                            const char *meta_ptr);

int inject_remote_trade(long long amount_micros);

int ecobridge_query_neff_vectorized(long long current_ts, double tau, double *out_result);

int ecobridge_compute_batch_prices(uint64_t count,
                                   double neff,
                                   const TradeContext *ctx_ptr,
                                   const MarketConfig *cfg_ptr,
                                   const double *hist_avgs_ptr,
                                   const double *lambdas_ptr,
                                   double *results_ptr);

int ecobridge_compute_price_final(double base,
                                  double n_eff,
                                  double lambda,
                                  double epsilon,
                                  double *out_result);

int ecobridge_compute_tier_price(double base, double qty, int is_sell, double *out_result);

int ecobridge_compute_price_humane(double base,
                                   double n_eff,
                                   double trade_amount,
                                   double lambda,
                                   double epsilon,
                                   double *out_result);

int ecobridge_compute_price_bounded(double base,
                                    double n_eff,
                                    double amt,
                                    double lambda,
                                    double eps,
                                    double hist_avg,
                                    double *out_result);

int ecobridge_calc_inflation(double current_heat, double m1, double *out_result);

int ecobridge_calc_stability(long long last_ts, long long curr_ts, double *out_result);

int ecobridge_calc_decay(double heat, double rate, double *out_result);

int ecobridge_get_health_stats(uint64_t *out_total, uint64_t *out_dropped);

int ecobridge_calculate_epsilon(const TradeContext *ctx_ptr,
                                const MarketConfig *cfg_ptr,
                                double *out_result);

int ecobridge_compute_transfer_check(TransferResult *out_result,
                                     const TransferContext *ctx_ptr,
                                     const RegulatorConfig *cfg_ptr);

int ecobridge_get_dynamic_limit(long long play_time_secs,
                                double base,
                                double rate,
                                double max,
                                double *out_result);

int ecobridge_compute_pid_adjustment(PidState *pid_ptr,
                                     double target,
                                     double current,
                                     double dt,
                                     double inflation,
                                     double market_heat,
                                     double *out_result);

int ecobridge_reset_pid_state(PidState *pid_ptr);

#endif  /* ECOBRIDGE_RUST_H */
